### ISSUE TITLE
Simplificar tablas de seguimiento de contrato cuando no hay límites

### ISSUE THREAD

**Issue by ainsu23** [FundacionAIS/aisalud#48]
**¿Tu solicitud esta relacionada con algún problema? Describelo.**
Cuando un usuario final no contempla límites superiores e inferiores en la frecuencia contratada, se observan 3 tablas con la misma información.

**Describe la solución que deseas**
Cuando no existan límites, eliminar las 3 tablas y simplificarla en 1 sola.

**Describe alternativas que has considerado**
Cuando no existan límites, eliminar las 3 tablas y simplificarla en 1 sola con las siguientes columnas:
- frecuencia mensual contratada
- valor mensual base
- valor del contrato,
- manteniendo unidad de conteo y agrupador
Cuando exista límites dejar como está actualmente.

**Comment by andyquinterom** [comment]
Pasemos este issue a la versión 21.09.1 o a una revisión de 21.08
